version: "3.8"

services:
  api:
    build: .
    container_name: event_management_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+pymysql://admin:admin123@mysql/event_db
      - SECRET_KEY=5f2a7b8e9c1d4f0a6d3e
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: event_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
